#!/usr/bin/env python3
"""
rst2tags.py — Generate Geany-compatible global tags files from
              prezento RST files containing .. slido:: directives.

Claud.ai

HOW GEANY USES THIS:
──────────────────────────────────────────────────────────────────
  1. One-shot generation (manual):
       python3 rst2tags.py slides/           → writes slides.rst.tags
       python3 rst2tags.py slides/ -o myproject.rst.tags
     Then in Geany: Tools ▸ Load Tags File ▸ select the .rst.tags file
     — OR — copy it to  ~/.config/geany/tags/   and restart Geany.

  2. Auto-regeneration on every save (recommended):
     In Geany: Build ▸ Set Build Commands ▸ "Independent commands"
       Label:   Refresh tags
       Command: python3 /path/to/rst2tags.py %d -o /path/to/slides.rst.tags
     Press F9 (or the build button) to refresh; Geany auto-reloads
     tags files that are already loaded.

  3. Watch mode (background auto-refresh):
       python3 rst2tags.py slides/ --watch
     Requires the `watchdog` package:  pip install watchdog

  4. For the GeanyCtags plugin (geany-plugins):
     The plugin runs Universal Ctags on the project. Combine with
     the  prezento.ctags  config file (also generated by this
     script with  --write-ctags-config) so ctags recognises slido.

TAG FILE FORMAT (Geany-compatible):
──────────────────────────────────────────────────────────────────
  Geany accepts CTags format v2 (same as Universal Ctags output).
  The file must be named  <something>.<lang_ext>.tags  where
  <lang_ext> is a recognised file extension for the filetype.
  For RST  →  *.rst.tags   is the correct suffix.

  Tags appear in:
    • Sidebar Symbols panel  (for any open .rst file)
    • Autocomplete (Ctrl+Space)
    • Go to Tag   (Ctrl+.)

SYMBOLS EXTRACTED:
──────────────────────────────────────────────────────────────────
  p  prezento  — presentation title  (.. prezento:: …)
  s  slide     — slide title         (.. slido:: …)
  f  function  — code block          (.. code:: …)
  c  class     — container           (.. container:: …)
  h  heading   — RST heading
"""

import re
import sys
import argparse
import time
from pathlib import Path

# ── Symbol extraction ─────────────────────────────────────────────────────────

# Maps directive name → (kind_letter, kind_name)
DIRECTIVE_KINDS = {
    'slido':     ('s', 'slide'),
    'prezento':  ('p', 'prezentation'),
    'code':      ('f', 'code-block'),
    'code-block':('f', 'code-block'),
    'container': ('c', 'container'),
    'graphviz':  ('g', 'graphviz'),
    'yographviz':('g', 'graphviz'),
}

# RST heading underline characters (in decreasing precedence)
HEADING_CHARS = r'[=\-~^"\'`#+*!@$%&]'

def extract_symbols(path: Path, base_dir: Path | None = None):
    """
    Yield (name, kind_letter, kind_name, lineno, pattern) tuples
    for every symbol found in *path*.
    """
    try:
        text = path.read_text(encoding='utf-8', errors='replace')
    except OSError:
        return

    lines = text.splitlines()
    n = len(lines)

    # Use a relative path in the tag record if base_dir is provided
    if base_dir:
        try:
            file_ref = str(path.relative_to(base_dir))
        except ValueError:
            file_ref = str(path)
    else:
        file_ref = str(path)

    # Use forward slashes for cross-platform compatibility
    file_ref = file_ref.replace('\\', '/')

    i = 0
    while i < n:
        raw = lines[i]
        stripped = raw.strip()

        # ── Directives ────────────────────────────────────────────────────
        m = re.match(r'^\.\.\s+(\S+?)::(?:\s+(.*))?$', stripped)
        if m:
            directive = m.group(1).lower()
            argument  = (m.group(2) or '').strip()
            if directive in DIRECTIVE_KINDS and argument:
                kind_letter, kind_name = DIRECTIVE_KINDS[directive]
                # Escape forward-slashes in the search pattern
                pattern = raw.rstrip().replace('/', '\\/')
                yield (argument, kind_letter, kind_name, i + 1, pattern, file_ref)

        # ── RST headings (text line + underline line) ─────────────────────
        elif (stripped
              and not stripped.startswith('..')
              and i + 1 < n):
            under = lines[i + 1].strip()
            if (under
                and re.match(fr'^{HEADING_CHARS}+$', under)
                and len(under) >= len(stripped) - 2):
                pattern = raw.rstrip().replace('/', '\\/')
                yield (stripped, 'h', 'heading', i + 1, pattern, file_ref)
                i += 2           # skip the underline too
                continue

        i += 1


def collect_all_symbols(source: Path):
    """Walk *source* recursively and collect symbols from every .rst file."""
    symbols = []
    rst_files = sorted(source.rglob('*.rst')) if source.is_dir() else [source]
    for f in rst_files:
        for sym in extract_symbols(f, base_dir=source if source.is_dir() else None):
            symbols.append(sym)
    return symbols


# ── Tags file writer ──────────────────────────────────────────────────────────

def write_tags_file(symbols, output: Path, source_label: str = ''):
    """
    Write a CTags v2 format tags file that Geany can load.

    File naming convention Geany expects:
        <anything>.rst.tags   ← for RST filetype
    """
    # Sort case-insensitively on tag name
    symbols.sort(key=lambda s: s[0].lower())

    with output.open('w', encoding='utf-8', newline='\n') as f:
        # Header (Geany ignores lines starting with '!')
        f.write('!_TAG_FILE_FORMAT\t2\t/extended format/\n')
        f.write('!_TAG_FILE_SORTED\t1\t/0=unsorted, 1=sorted, 2=foldcase/\n')
        f.write('!_TAG_FILE_ENCODING\tutf-8\t//\n')
        if source_label:
            f.write(f'!_TAG_FILE_AUTHOR\tprezento rst2tags.py\t/source: {source_label}/\n')

        for name, kind_letter, kind_name, lineno, pattern, file_ref in symbols:
            # CTags extended format:
            #   tagname  TAB  file  TAB  /^pattern$/;"  TAB  kind  TAB  line:N
            safe_pattern = pattern.replace('\\', '\\\\')
            f.write(
                f'{name}\t{file_ref}\t/^{safe_pattern}$/;"\t'
                f'{kind_letter}\tline:{lineno}\n'
            )

    return len(symbols)


# ── Universal Ctags config writer ─────────────────────────────────────────────

CTAGS_CONFIG = r"""# prezento.ctags — Universal Ctags configuration for prezento RST files.
#
# INSTALL:  copy to  ~/.ctags.d/prezento.ctags
# USAGE:    ctags -n --fields=EfiklsZSt -R -o slides.rst.tags slides/
#
# Works with:
#   • Universal Ctags  (recommended)  https://github.com/universal-ctags/ctags
#   • The GeanyCtags Geany plugin     https://plugins.geany.org/geanyctags.html
#
# After installing, generate tags:
#   ctags --options=$HOME/.ctags.d/prezento.ctags \
#         -n --fields=EfiklsZSt -R -o project.rst.tags /path/to/slides/

# ── Define a new language that maps to .rst files ──────────────────────────
--langdef=PrezRST
--langmap=PrezRST:.rst
--languages=PrezRST

# ── Kind definitions ────────────────────────────────────────────────────────
--kinddef-PrezRST=p,prezentation,presentation title
--kinddef-PrezRST=s,slide,slide title
--kinddef-PrezRST=h,heading,RST section heading
--kinddef-PrezRST=f,codeblock,code block
--kinddef-PrezRST=c,container,container directive
--kinddef-PrezRST=g,graphviz,graphviz diagram

# ── Regex patterns ──────────────────────────────────────────────────────────
# .. prezento:: Title
--regex-PrezRST=/^\.\. prezento::\s+(.+)/\1/p/{exclusive}

# .. slido:: Slide Title
--regex-PrezRST=/^\.\. slido::\s+(.+)/\1/s/{exclusive}

# .. code:: language  or  .. code-block:: language
--regex-PrezRST=/^\.\. code(?:-block)?::\s+(.+)/\1/f/{exclusive}

# .. container:: classes
--regex-PrezRST=/^\.\. container::\s+(.+)/\1/c/{exclusive}

# .. graphviz:: / .. yographviz::
--regex-PrezRST=/^\.\. (?:y?o?graphviz)::/graphviz/g/{exclusive}

# RST headings  (text followed by a line of ====, ----, ~~~~, etc.)
--regex-PrezRST=/^([A-Za-z0-9][^\n]+)\n[=\-~^"'`#+*]{3,}/\1/h/

# ── Output fields recommended by Geany ─────────────────────────────────────
# Use these flags when calling ctags:
#   ctags -n --fields=EfiklsZSt -R ...
"""

def write_ctags_config(output: Path):
    output.write_text(CTAGS_CONFIG, encoding='utf-8')
    print(f'Written ctags config: {output}')
    print(f'  Install: cp {output} ~/.ctags.d/prezento.ctags')


# ── Geany filetype override ───────────────────────────────────────────────────

GEANY_FILETYPE = """# ~/.config/geany/filedefs/filetypes.restructuredtext
#
# Override Geany's built-in RST filetype definition to also recognise
# prezento-specific directives in the symbol sidebar.
#
# INSTALL:
#   mkdir -p ~/.config/geany/filedefs
#   cp this_file ~/.config/geany/filedefs/filetypes.restructuredtext
#   Restart Geany.
#
# HOW IT WORKS:
#   Geany parses open files using its built-in TagManager.  For RST
#   the built-in parser only handles headings.  The [tag_regexes]
#   section below adds custom regex patterns on top so that
#   .. slido:: and .. prezento:: lines also appear in the sidebar.
#   Requires Geany >= 1.36.
#
# NOTE: The symbol sidebar shows symbols from the *current open file*.
#       Symbols from other files (global tags) are available via
#       autocompletion and Ctrl+. (Go to Tag) after loading the .tags
#       file with Tools ▸ Load Tags File.

[settings]
# Keep default RST extension mapping
extension=rst
mime_type=text/x-rst
# Keep built-in lexer (syntax highlighting)
lexer_filetype=reStructuredText

[tag_regexes]
# Format:  /regex_pattern/tag_name/kind_letter/flags
#
# Match:  .. slido:: Slide Title
0=/^\\.\\.\\s+slido::\\s+(.+)/\\1/s/
#
# Match:  .. prezento:: Presentation Title
1=/^\\.\\.\\s+prezento::\\s+(.+)/\\1/p/
#
# Match:  .. code:: language
2=/^\\.\\.\\s+code(?:-block)?::\\s+(.+)/\\1/f/
"""

def write_geany_filetype(output: Path):
    output.write_text(GEANY_FILETYPE, encoding='utf-8')
    print(f'Written Geany filetype override: {output}')
    install = Path.home() / '.config/geany/filedefs/filetypes.restructuredtext'
    print(f'  Install: cp {output} {install}')


# ── Watch mode ────────────────────────────────────────────────────────────────

def watch_mode(source: Path, output: Path):
    """Regenerate the tags file whenever an .rst file changes."""
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler
    except ImportError:
        print('Watch mode requires the watchdog package:', file=sys.stderr)
        print('  pip install watchdog', file=sys.stderr)
        sys.exit(1)

    def regenerate(reason=''):
        symbols = collect_all_symbols(source)
        n = write_tags_file(symbols, output, str(source))
        print(f'[{time.strftime("%H:%M:%S")}] Regenerated {output.name}'
              f' ({n} tags){" — " + reason if reason else ""}')

    class RSTHandler(FileSystemEventHandler):
        def on_any_event(self, event):
            if not event.is_directory and str(event.src_path).endswith('.rst'):
                regenerate(Path(event.src_path).name)

    regenerate('initial')
    observer = Observer()
    watch_path = str(source) if source.is_dir() else str(source.parent)
    observer.schedule(RSTHandler(), watch_path, recursive=True)
    observer.start()
    print(f'Watching {watch_path} for .rst changes (Ctrl+C to stop)…')
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(
        description='Generate a Geany-compatible tags file from prezento RST files.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        'source',
        type=Path,
        nargs='?',
        default=Path('.'),
        help='RST file or directory to scan (default: current directory)',
    )
    p.add_argument(
        '-o', '--output',
        type=Path,
        default=None,
        help=(
            'Output .tags file path. '
            'Default: <source_dir_name>.rst.tags in current directory.'
        ),
    )
    p.add_argument(
        '--watch',
        action='store_true',
        help='Watch for changes and auto-regenerate the tags file (requires watchdog).',
    )
    p.add_argument(
        '--write-ctags-config',
        metavar='FILE',
        type=Path,
        default=None,
        help=(
            'Also write a Universal Ctags config file for use with '
            'GeanyCtags plugin or the ctags command line.'
        ),
    )
    p.add_argument(
        '--write-geany-filetype',
        metavar='FILE',
        type=Path,
        default=None,
        help=(
            'Also write a Geany filetype override file that adds '
            '.. slido:: and .. prezento:: to the sidebar symbol list. '
            'Install it to ~/.config/geany/filedefs/filetypes.restructuredtext'
        ),
    )
    p.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Print each symbol found.',
    )
    args = p.parse_args()

    source = args.source.resolve()
    if not source.exists():
        print(f'Error: {source} does not exist.', file=sys.stderr)
        sys.exit(1)

    # Determine output path
    if args.output:
        output = args.output
    else:
        stem = source.name if source.is_dir() else source.stem
        output = Path(f'{stem}.rst.tags')

    # Optional extra files
    if args.write_ctags_config:
        write_ctags_config(args.write_ctags_config)
    if args.write_geany_filetype:
        write_geany_filetype(args.write_geany_filetype)

    # Watch mode
    if args.watch:
        watch_mode(source, output)
        return

    # Single-shot generation
    symbols = collect_all_symbols(source)
    n = write_tags_file(symbols, output, str(source))

    if args.verbose:
        for name, kind_letter, kind_name, lineno, _pat, file_ref in symbols:
            print(f'  [{kind_letter}] {name:50s}  {file_ref}:{lineno}')

    print(f'Written {output}  ({n} tags from {source})')
    print()
    print('Load in Geany:  Tools ▸ Load Tags File')
    print(f'Auto-load:      cp {output} ~/.config/geany/tags/')


if __name__ == '__main__':
    main()
